---
# Title: role-automatic-updates
#
# Author: Bitfinity / L. Rutten
# Owener: Bitfinity / L. Rutten
#
# File: tasks/main.yml
#
# Description:
#   This role contains the tasks for configuring
#   automatic updates for different server.
#
- name: "Include tasks/ubuntu/01-postfix.yml"
  include_tasks: tasks/ubuntu/01-postfix.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_architecture == "x86_64"
    #- ansible_distribution_version == "22.04"

    
- name: "Include tasks/ubuntu/02-automatic-updates-v1.yml"
  include_tasks: tasks/ubuntu/02-automatic-updates-v1.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_architecture == "x86_64"
    #- ansible_distribution_version == "22.04"
