---
# Title: role-automatic-updates
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/ubuntu/01-automatic-updates-v1.yml
#
# Description:
#   This role contains the tasks for configuring
#   automatic updates for different server.
#
# Source(s):
#   - https://linuxopsys.com/topics/ubuntu-automatic-updates
#   - https://haydenjames.io/how-to-enable-unattended-upgrades-on-ubuntu-debian/
#
- name: "Run the equivalent of (apt-get update)"
  ansible.builtin.apt:
    update_cache: yes
    
- name: "Install APT packages"
  ansible.builtin.apt:
    pkg:
    - unattended-upgrades
    - update-notifier-common
    
- name: "Enable and start dependend systemd service(s)"
  ansible.builtin.systemd:
    state: started
    name: unattended-upgrades
    enabled: yes

- name: "Configure unattended-upgrades service"
  ansible.builtin.template:
    src: ubuntu/50unattended-upgrades-v1.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'
    
- name: "Enable automatic updates"
  ansible.builtin.template:
    src: ubuntu/20auto-upgrades-v1.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
 
